apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-operator
  namespace: kafka
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafka-operator
rules:
  - apiGroups: ["kafka.yavari.afshin.se"]
    resources:
      - kafkaclusters
      - kafkaclusters/status
      - kafkaclusters/finalizers
      - kafkanodepools
      - kafkanodepools/status
      - kafkanodepools/finalizers
      - kafkapodsets
      - kafkapodsets/status
      - kafkapodsets/finalizers
      - kafkarbacs
      - kafkarbacs/status
      - kafkarbacs/finalizers
      - kafkaproxies
      - kafkaproxies/status
      - kafkaproxies/finalizers
      - apicurioregistries
      - apicurioregistries/status
      - apicurioregistries/finalizers
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "persistentvolumeclaims", "configmaps", "services", "secrets", "namespaces", "events"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["monitoring.coreos.com"]
    resources: ["servicemonitors"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["multicluster.x-k8s.io"]
    resources: ["serviceexports"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kafka-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kafka-operator
subjects:
  - kind: ServiceAccount
    name: kafka-operator
    namespace: kafka
