import type { ProjectDocument } from '../model/project'
import { generateTopology } from './javaTopology'
import { generateConnectorConfigs } from './connectorConfig'
import { generateRecordClasses } from './javaRecords'
import { computeOutputTypes, generateOutputRecord } from './outputTypes'

/** One generated source file. */
export interface GeneratedFile {
  path: string
  content: string
}

const JAVA_DIR = 'src/main/java/org/acme/kafka'

function applicationProperties(doc: ProjectDocument): string {
  const appId =
    (doc.meta.name || 'kafka-streams-app')
      .trim()
      .replace(/\s+/g, '-')
      .toLowerCase() || 'kafka-streams-app'
  const topics = doc.catalog.topics.map((t) => t.name).join(',')
  return `# Generated by Kafka Editor
quarkus.kafka-streams.application-id=${appId}
quarkus.kafka-streams.bootstrap-servers=localhost:9092
quarkus.kafka-streams.topics=${topics}

kafka.bootstrap.servers=localhost:9092
`
}

const POM_XML = `<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.acme</groupId>
  <artifactId>kafka-streams-app</artifactId>
  <version>1.0.0-SNAPSHOT</version>

  <properties>
    <maven.compiler.release>17</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>
    <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
    <quarkus.platform.version>3.17.4</quarkus.platform.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>\${quarkus.platform.group-id}</groupId>
        <artifactId>\${quarkus.platform.artifact-id}</artifactId>
        <version>\${quarkus.platform.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-kafka-streams</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-arc</artifactId>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>\${quarkus.platform.group-id}</groupId>
        <artifactId>quarkus-maven-plugin</artifactId>
        <version>\${quarkus.platform.version}</version>
        <extensions>true</extensions>
        <executions>
          <execution>
            <goals>
              <goal>build</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
`

/** Generate the full Quarkus project for a topology document. */
export function generateProject(doc: ProjectDocument): GeneratedFile[] {
  const files: GeneratedFile[] = [
    { path: 'pom.xml', content: POM_XML },
    {
      path: 'src/main/resources/application.properties',
      content: applicationProperties(doc),
    },
    {
      path: `${JAVA_DIR}/TopologyProducer.java`,
      content: generateTopology(doc),
    },
  ]

  // Java type files — record types (with nested classes) and operator outputs.
  // Deduplicate by path so colliding class names produce one file.
  const seen = new Set<string>(files.map((f) => f.path))
  const addJava = (className: string, content: string) => {
    const path = `${JAVA_DIR}/${className}.java`
    if (seen.has(path)) return
    seen.add(path)
    files.push({ path, content })
  }
  for (const recordType of doc.recordTypes) {
    for (const cls of generateRecordClasses(recordType, doc.recordTypes)) {
      addJava(cls.className, cls.content)
    }
  }
  for (const outputType of computeOutputTypes(doc).values()) {
    addJava(outputType.className, generateOutputRecord(outputType))
  }

  files.push(...generateConnectorConfigs(doc))
  return files
}
