apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-client-app-consumer
  namespace: kafka
  labels:
    app: kafka-client-app
    role: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-client-app
      role: consumer
  template:
    metadata:
      labels:
        app: kafka-client-app
        role: consumer
    spec:
      terminationGracePeriodSeconds: 20
      containers:
        - name: app
          image: image-registry.openshift-image-registry.svc:5000/kafka/kafka-client-app:1.0.0
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: TLS_KEYSTORE_PATH
              value: /etc/tls/keystore.p12
            - name: TLS_TRUSTSTORE_PATH
              value: /etc/tls/truststore.p12
          envFrom:
            - secretRef:
                name: kafka-client-app-tls-passwords
                optional: true
            - configMapRef:
                name: kafka-client-app-consumer
          volumeMounts:
            - name: tls
              mountPath: /etc/tls
              readOnly: true
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests: { cpu: 100m, memory: 256Mi }
            limits: { memory: 512Mi }
      volumes:
        - name: tls
          secret:
            secretName: kafka-client-app-tls
            optional: true
