package se.afshin.yavari.kafka.operator.backup;

import jakarta.enterprise.context.ApplicationScoped;
import se.afshin.yavari.kafka.operator.crd.BackupTopicSelector;
import se.afshin.yavari.kafka.operator.crd.KafkaBackup;
import se.afshin.yavari.kafka.operator.crd.KafkaBackupSpec;

import java.util.List;

/**
 * Renders the osodevops kafka-backup {@code backup.yaml} config from a {@link KafkaBackup}.
 * The workload connects direct to the broker headless service; TLS material is read from
 * mounted PEM files (no PKCS12 conversion — the tool is a pure-Rust rustls client).
 */
@ApplicationScoped
public class BackupConfigBuilder {

    public String build(KafkaBackup cr, ResolvedBackupEndpoint endpoint) {
        KafkaBackupSpec spec = cr.getSpec();
        StringBuilder sb = new StringBuilder();
        sb.append("# Generated by kafka-operator — do not edit.\n");
        sb.append("mode: backup\n");
        sb.append("backup_id: ").append(BackupYaml.q(cr.resolvedBackupId())).append("\n\n");

        sb.append("source:\n");
        sb.append("  bootstrap_servers:\n");
        sb.append("    - ").append(BackupYaml.q(endpoint.bootstrap())).append('\n');
        appendSecurity(sb, endpoint.hasTls());
        appendTopics(sb, spec.getTopics());
        sb.append('\n');

        BackupStorageMounts.appendStorageBlock(sb, spec.getStorage());
        sb.append('\n');

        sb.append("backup:\n");
        sb.append("  compression: ").append(spec.getCompression().name().toLowerCase()).append('\n');
        if (spec.getCompressionLevel() != null) {
            sb.append("  compression_level: ").append(spec.getCompressionLevel()).append('\n');
        }
        if (spec.getAdditionalConfig() != null) {
            spec.getAdditionalConfig().forEach((k, v) ->
                    sb.append("  ").append(k).append(": ").append(BackupYaml.q(v)).append('\n'));
        }
        return sb.toString();
    }

    /** Renders the {@code security:} sub-block. mTLS: SSL with CA + client cert + key from
     *  the mounted PEM Secret. Plaintext clusters get no block. */
    static void appendSecurity(StringBuilder sb, boolean tls) {
        if (!tls) {
            return;
        }
        sb.append("  security:\n");
        sb.append("    security_protocol: SSL\n");
        sb.append("    ssl_ca_location: ")
                .append(BackupYaml.q(BackupPaths.TLS_DIR + "/ca.crt")).append('\n');
        sb.append("    ssl_certificate_location: ")
                .append(BackupYaml.q(BackupPaths.TLS_DIR + "/tls.crt")).append('\n');
        sb.append("    ssl_key_location: ")
                .append(BackupYaml.q(BackupPaths.TLS_DIR + "/tls.key")).append('\n');
    }

    /** Renders the {@code topics:} include/exclude sub-block. */
    static void appendTopics(StringBuilder sb, BackupTopicSelector topics) {
        BackupTopicSelector t = topics != null ? topics : new BackupTopicSelector();
        sb.append("  topics:\n");
        sb.append("    include:\n");
        for (String p : t.getInclude()) {
            sb.append("      - ").append(BackupYaml.q(p)).append('\n');
        }
        List<String> exclude = t.getExclude();
        if (exclude != null && !exclude.isEmpty()) {
            sb.append("    exclude:\n");
            for (String p : exclude) {
                sb.append("      - ").append(BackupYaml.q(p)).append('\n');
            }
        }
    }
}
