package se.afshin.yavari.kafka.operator.backup;

import jakarta.enterprise.context.ApplicationScoped;
import se.afshin.yavari.kafka.operator.crd.BackupStorageSpec;
import se.afshin.yavari.kafka.operator.crd.KafkaRestore;
import se.afshin.yavari.kafka.operator.crd.KafkaRestoreSpec;
import se.afshin.yavari.kafka.operator.crd.RestoreTimeWindow;

/**
 * Renders the osodevops kafka-backup {@code restore.yaml} config from a {@link KafkaRestore}.
 * The {@code storage} and {@code backupId} are resolved by the reconciler (inline or via a
 * referenced {@link se.afshin.yavari.kafka.operator.crd.KafkaBackup}).
 */
@ApplicationScoped
public class RestoreConfigBuilder {

    public String build(KafkaRestore cr, ResolvedBackupEndpoint endpoint,
                        BackupStorageSpec storage, String backupId) {
        KafkaRestoreSpec spec = cr.getSpec();
        StringBuilder sb = new StringBuilder();
        sb.append("# Generated by kafka-operator — do not edit.\n");
        sb.append("mode: restore\n");
        sb.append("backup_id: ").append(BackupYaml.q(backupId)).append("\n\n");

        sb.append("target:\n");
        sb.append("  bootstrap_servers:\n");
        sb.append("    - ").append(BackupYaml.q(endpoint.bootstrap())).append('\n');
        BackupConfigBuilder.appendSecurity(sb, endpoint.hasTls());
        BackupConfigBuilder.appendTopics(sb, spec.getTopics());
        sb.append('\n');

        BackupStorageMounts.appendStorageBlock(sb, storage);
        sb.append('\n');

        sb.append("restore:\n");
        sb.append("  create_topics: ").append(spec.isCreateTopics()).append('\n');
        sb.append("  dry_run: ").append(spec.isDryRun()).append('\n');

        RestoreTimeWindow window = spec.getTimeWindow();
        if (window != null && window.getStartMillis() != null) {
            sb.append("  time_window_start: ").append(window.getStartMillis()).append('\n');
        }
        if (window != null && window.getEndMillis() != null) {
            sb.append("  time_window_end: ").append(window.getEndMillis()).append('\n');
        }

        if (spec.getTopicMapping() != null && !spec.getTopicMapping().isEmpty()) {
            sb.append("  topic_mapping:\n");
            spec.getTopicMapping().forEach((from, to) ->
                    sb.append("    ").append(from).append(": ").append(BackupYaml.q(to)).append('\n'));
        }

        sb.append("  reset_consumer_offsets: ").append(spec.isRestoreOffsets()).append('\n');
        if (spec.isRestoreOffsets()
                && spec.getConsumerGroups() != null && !spec.getConsumerGroups().isEmpty()) {
            sb.append("  consumer_groups:\n");
            for (String g : spec.getConsumerGroups()) {
                sb.append("    - ").append(BackupYaml.q(g)).append('\n');
            }
        }

        if (spec.getAdditionalConfig() != null) {
            spec.getAdditionalConfig().forEach((k, v) ->
                    sb.append("  ").append(k).append(": ").append(BackupYaml.q(v)).append('\n'));
        }
        return sb.toString();
    }
}
